### ISSUE TITLE
Titles not found.

### ISSUE THREAD

**Issue by naxeras** [L10N37/PS2-ISO-Batch-Renamer-#4]
Hi, the last version is working great not more stuck.

These games was not detected:

3D Kakutou Tkool 2 (Japan).iso
Avventure di Lupin III, Le - Lupin la Morte, Zenigata l'Amore (Italy).iso
Cy Girls (Europe) (En,Fr,Es) (Aska Disc).iso
Grand Theft Auto - Vice City Stories (Europe, Australia) (En,Fr,De,Es,It).iso
MegaRace 3 - Nanotech Disaster (Europe) (En,Fr,De,Es,It).iso
Mercenaries - Playground of Destruction (Europe) (Es,It).iso
Mercenaries 2 - World in Flames (Spain).iso
Ratchet & Clank - Size Matters (Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,No,Da,Fi,Pl,Hr).iso
Valkyrie Profile 2 - Silmeria (Spain).iso
Venus & Braves - Majo to Megami to Horobi no Yogen (Japan).iso

How can I help you to add in the DB?

Regards.

**Comment by L10N37** [comment]
"How can I help you to add in the DB?"

Just like this :) 

I will update the DB in the repo tomorrow (well, later today)

**Comment by L10N37** [comment]
All added to DB file in repo, haven't added to the release but people can grab the updated one from the root of the repo.

SLPS-20318 3D Kakutou Tsukuru 2 [Enterbrain Collection] 
SLES-54973 Avventure di Lupin III, Le - Lupin la Morte, Zenigata l'Amore 
SLES-82019 Cy Girls (Aska Disc) 
SLES-82021 Cy Girls (Aska Disc) 
SLES-82018 Cy Girls (Ice Disc) 
SLES-82020 Cy Girls (Ice Disc) 
SCES-54623 Grand Theft Auto - Vice City Stories 
SLES-54623 Grand Theft Auto - Vice City Stories 
SLPM-66917 Grand Theft Auto - Vice City Stories 
SLUS-21590 Grand Theft Auto - Vice City Stories 
SLES-50903 MegaRace 3 - Nanotech Disaster 
SLUS-20932 Mercenaries - Playground of Destruction 
SLES-52588 Mercenaries - Playground of Destruction 
SLES-52590 Mercenaries - Playground of Destruction 
SLES-53008 Mercenaries - Playground of Destruction 
SLES-52589 Mercenaries - Playground of Destruction 
SLED-52979 Mercenaries - Playground of Destruction (Demo)
SLES-54998 Mercenaries 2 - World in Flames 
SLES-54999 Mercenaries 2 - World in Flames 
SLES-54997 Mercenaries 2 - World in Flames 
SLES-55000 Mercenaries 2 - World in Flames 
SLES-55001 Mercenaries 2 - World in Flames 
SCES-55019 Ratchet & Clank - Size Matters 
SLES-54644 Valkyrie Profile 2 - Silmeria 
SLES-54645 Valkyrie Profile 2 - Silmeria 
SLES-54647 Valkyrie Profile 2 - Silmeria 
SLES-54646 Valkyrie Profile 2 - Silmeria 
SLES-54648 Valkyrie Profile 2 - Silmeria 
SLPS-25196 Venus & Braves - Majo to Megami to Horobi no Yogen 
SLPS-25195 Venus & Braves - Majo to Megami to Horobi no Yogen (Premium Box) 
SLPS-73236 Venus & Braves - Majo to Megami to Horobi no Yogen 
SCAJ-20012 Venus & Braves - Majo to Megami to Horobi no Yogen
